### ISSUE TITLE
[Major Bug] App no longer tracking

### ISSUE THREAD

**Issue by collectorgeneral** [redfish64/TinyTravelTracker#46]
General Information:
App details:
Version: 1.1.17; Source: F-droid
OS: Cyanogen OS 13.1.2 (Android 6.0.1)
Device: Oneplus One (aka A0001 aka Bacon)

Description:

The new 1.1.17 does not appear to record (or maybe display, not sure) locations whatsoever. I updated it today and went on with my routine, when I checked back, no points are on the map. The distance says 0 KM even though I travelled quite a bit. I downgraded to previous version and everything works fine, then again upgraded and the same issue arises.

**Comment by redfish64** [comment]
I found a corresponding crash report in the reported feedback, for what you are describing. It's affecting a large number of people, so I'm going ahead and reverting the change. But I'm still unsure what is causing it, and why I'm not affected. 

I'll keep looking at this. The new version, v1.1.18, which should build tonight, is simply a rollback of the change.

**Comment by collectorgeneral** [comment]
@redfish64 
Hm, I did not experience any crash per se.

Is your test device displaying all the points on the map as usual?

**Comment by redfish64** [comment]
The GPS service in the background is crashing. It displays nothing to the
user when this happens, but fails to record the point. I do get a
notification in the error log service if you have "Allow Error Reporting"
turned on.

**Comment by collectorgeneral** [comment]
Ah, that explains why no points are being recorded, though it is odd that there is no crash dialog box showing up.

**Comment by redfish64** [comment]
I believe this is fixed, so I'm closing this

**Comment by NitroNils** [comment]
Still experiencing no tracking episodes. How to.approach - file a new issue?
